Implement shares purchase flow
spine-examples/shareaware pull request #18
Opened 2023-03-31 09:31 UTC by Artem-Semenov-dev

This PR implements shares purchase flow.
The process modeling of the shares purchase flow:
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/44636928/229082711-a2d92ac9-6240-457b-ad24-385504512c14.png">

2023-03-31 10:42 UTC, Vladyslav-Kuksiuk reviewed
@Artem-Semenov-dev please see my comments.

2023-03-31 10:42 UTC, Vladyslav-Kuksiuk commented on server/src/main/java/io/spine/examples/shareaware/server/wallet/MoneyCalculator.java
> +     *     <li>its nanos to be in 0..100 range</li>
```suggestion
     *     <li>its nanos to be in 0..{@code MAX_NANOS_AMOUNT} range</li>
```

2023-03-31 10:42 UTC, Vladyslav-Kuksiuk commented on server/src/test/java/io/spine/examples/shareaware/server/investment/SharesPurchaseTest.java
> +        void event() {
There is no event check in this method.
```suggestion
        void walletState() {
```

2023-03-31 10:42 UTC, Vladyslav-Kuksiuk commented on server/src/test/java/io/spine/examples/shareaware/server/investment/SharesPurchaseTest.java
> +        void debitMoney() {
Based on other method names:
```suggestion
        void reservedMoneyDebited() {
```
or
```suggestion
        void moneyDebited() {
```

2023-03-31 10:42 UTC, Vladyslav-Kuksiuk commented on server/src/test/java/io/spine/examples/shareaware/server/investment/SharesPurchaseTest.java
> +    class InvestmentState {
I suggest having a test on emitting the `SharesAdded` event.

2023-03-31 10:42 UTC, Vladyslav-Kuksiuk commented on server/src/test/java/io/spine/examples/shareaware/server/investment/SharesPurchaseTest.java
> +            InvestmentId investmentId = InvestmentId
I think it's better to extract this to the corresponding TestEnv.

2023-03-31 10:42 UTC, Vladyslav-Kuksiuk commented on server/src/test/java/io/spine/examples/shareaware/server/investment/SharesPurchaseTest.java
> +    @DisplayName("be leb by shares purchase process")
```suggestion
    @DisplayName("be led by shares purchase process")
```

2023-03-31 10:42 UTC, Vladyslav-Kuksiuk commented on server/src/test/java/io/spine/examples/shareaware/server/investment/SharesPurchaseTest.java
> +        @DisplayName("which emits the `SharesPurchasedFailed` event when insufficient funds in the wallet")
```suggestion
        @DisplayName("which emits the `SharesPurchaseFailed` event when insufficient funds in the wallet")
```

2023-03-31 10:42 UTC, Vladyslav-Kuksiuk commented on server/src/test/java/io/spine/examples/shareaware/server/investment/given/RejectingMarket.java
> +     * Emits the {@code SharesObtained} event when rejection mode if off
```suggestion
     * Emits the {@code SharesObtained} event when rejection mode is disabled
```

2023-03-31 15:58 UTC, armiol requested changes
@Artem-Semenov-dev please see my comments.

2023-03-31 15:58 UTC, armiol commented on model/src/main/java/io/spine/examples/shareaware/wallet/MoneyReservationSignal.java
> +     * <p>In case when neither {@code WithdrawalId} nor {@code PurchaseId} is not set in the corresponding {@code OperationId},
Please make sure to fit 100 symbols wide.

2023-03-31 15:58 UTC, armiol commented on model/src/main/java/io/spine/examples/shareaware/wallet/MoneyReservationSignal.java
> +     * <a href="https://protobuf.dev/reference/java/java-generated/#:~:text=static%20Foo%20getDefaultInstance,its%20newBuilderForType()%20method.">
Let's not put the link here.
```
It will return the default instance of ...
```

2023-03-31 15:58 UTC, armiol commented on model/src/main/proto/spine_examples/shareaware/identifiers.proto
> +    spine.core.UserId owner = 2 [(required) = true];
Please allow an empty line above.

2023-03-31 15:58 UTC, armiol commented on server/src/main/java/io/spine/examples/shareaware/server/investment/InvestmentAggregate.java
> + * The Investment aggregate is responsible for managing the shares of one type
Let's shorten:
```
Manages the shares of a single type purchased by a particular ShareAware user.
```

2023-03-31 15:58 UTC, armiol commented on server/src/main/java/io/spine/examples/shareaware/server/investment/InvestmentAggregate.java
> +        if (!state().hasId()) {
We want to set the ID in any case. The event has already happened.

2023-03-31 15:58 UTC, armiol commented on server/src/main/java/io/spine/examples/shareaware/server/investment/SharesPurchaseProcess.java
> +     * Ends the process successfully when reserved money was debited from the wallet.
Technically, such sentences should look like this:
```
Ends the process successfully when reserved money are debited from the wallet.
```

Please do some research in terms of English grammar. Here is [one thing](https://learnenglish.britishcouncil.org/grammar/english-grammar-reference/verbs-time-clauses-if-clauses#:~:text=In%20time%20clauses%20with%20words,after%20they%20have%20had%20dinner.) to start from.

2023-03-31 15:58 UTC, armiol commented on server/src/main/java/io/spine/examples/shareaware/server/market/package-info.java
> + * Provides server-side classes for working with shares market imitation.
I think the package is about working with market. It's a completely different matter that we now have an implementation which just _imitates_ things.

2023-03-31 15:58 UTC, armiol commented on server/src/main/java/io/spine/examples/shareaware/server/wallet/MoneyCalculator.java
> +    /**
```

    /**
     * Checks {@code Money} object for:
     * 
     * <ul>
     *     <li>being non-nullable,</li>
     *     <li>its units to be non-negative,</li>
     *     <li>its nanos to be in 0..{@code MAX_NANOS_AMOUNT} range.</li>
     * </ul>
     */
```

2023-03-31 15:58 UTC, armiol commented on server/src/main/java/io/spine/examples/shareaware/server/wallet/MoneyCalculator.java
> +    private static void checkMoneyArgument(Money money) {
How about 
```
private static void checkArgument(Money money) { ... }
```

2023-03-31 15:58 UTC, armiol commented on server/src/test/java/io/spine/examples/shareaware/server/investment/given/RejectingMarket.java
> + * <p>It has the functionality to enter the rejection mode,
```
It is possible to put it into the "rejection" mode, making it reject all commands handled.
```

2023-03-31 15:58 UTC, armiol commented on server/src/test/java/io/spine/examples/shareaware/server/investment/given/RejectingMarket.java
> +    public static void switchToRejectionMode() {
Please document.

Same below.

2023-04-03 16:44 UTC, armiol approved these changes
@Artem-Semenov-dev LGTM with some comments to address.

2023-04-03 16:44 UTC, armiol commented on server/src/main/java/io/spine/examples/shareaware/server/wallet/MoneyCalculator.java
>       * or false otherwise.
Weren't there enough space on the previous line?

2023-04-03 16:44 UTC, armiol commented on model/src/main/java/io/spine/examples/shareaware/wallet/MoneyReservationSignal.java
> +     * Verifies that signal is a part of the purchase process or not.
"Tells whether this signal is a part of the purchase process, or not".

"Verification" is something different.

2023-04-04 15:24 UTC, merged