Implement tool for reading shares from YAML file
spine-examples/shareaware pull request #26
Opened 2023-04-19 16:34 UTC by Artem-Semenov-dev

This PR implements `SharesReader` - the tool for reading the 'Share' instances from the YAML file. This is needed because of an idea to store shares that will be used in the application, in a file which is more convenient in usage than simple static storage.

2023-04-19 16:57 UTC, Vladyslav-Kuksiuk reviewed
Mostly LGTM, with minor comments.

2023-04-19 16:57 UTC, Vladyslav-Kuksiuk commented on model/src/main/java/io/spine/examples/shareaware/sharesreader/SharesReader.java
> +                    .collect(Collectors.toSet());
Please import `toSet()` statically.

2023-04-19 16:57 UTC, Vladyslav-Kuksiuk commented on model/src/main/java/io/spine/examples/shareaware/sharesreader/SharesReader.java
> +            throw illegalStateWithCauseOf(e);
I think it should be `IllegalArgumentException`.

2023-04-20 11:21 UTC, armiol requested changes
@Artem-Semenov-dev LGTM in general. Please see my comments though.

2023-04-20 11:21 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/examples/shareaware/dependency/Jackson.kt
> +object Jackson {
We usually have a comment which points to the original GitHub repo, or website.

See [this one](https://github.com/SpineEventEngine/config/blob/master/buildSrc/src/main/kotlin/io/spine/internal/dependency/BouncyCastle.kt), as an example.

2023-04-20 11:21 UTC, armiol commented on model/src/main/java/io/spine/examples/shareaware/sharesreader/SharesReader.java
> +     * <ul>
Use  the combination of `<pre>` and `{@code}` instead. Here is [an example](https://github.com/SpineEventEngine/core-java/blob/936f7195cd2118bcc1daa63bc66332c7fc9f21e2/client/src/main/java/io/spine/client/CommandRequest.java#L53).

2023-04-20 11:21 UTC, armiol commented on model/src/test/resources/sharesCredentials.yml
This is not "credentials".

2023-04-20 14:07 UTC, armiol requested changes
@Artem-Semenov-dev we are getting closer. Please see my comments.

2023-04-20 14:07 UTC, armiol commented on model/src/test/resources/testingShares.yml
Please rename to `testing-shares.yml`.

2023-04-20 14:07 UTC, armiol commented on model/src/main/proto/spine_examples/shareaware/share/share.proto
> +package spine_examples.shareaware.share;
I have asked to adjust the Java package only.

Let's leave the Proto message in the same folder and in the same Proto package.

2023-04-20 15:29 UTC, armiol approved these changes

2023-04-25 16:21 UTC, merged