Add functionality to purchase shares through the UI
spine-examples/shareaware pull request #38
Opened 2023-06-08 13:19 UTC by Artem-Semenov-dev

This PR adds functionality to purchase shares through the UI.
The view of the purchase process:
![Screen Recording 2023-06-08 at 16 12 33](https://github.com/spine-examples/shareaware/assets/44636928/3717bb5f-dc7d-4a89-b9f9-11597eba901d)

2023-06-08 14:40 UTC, Vladyslav-Kuksiuk reviewed
@Artem-Semenov-dev mostly LGTM, please see my comments.

2023-06-08 14:40 UTC, Vladyslav-Kuksiuk commented on client/src/main/kotlin/io/spine/examples/shareaware/client/MarketPage.kt
> +     * It needs to be shown to the user to inform about the result of the purchase operation.
I think it is redundant.

2023-06-08 14:40 UTC, Vladyslav-Kuksiuk commented on client/src/main/kotlin/io/spine/examples/shareaware/client/MarketPage.kt
> +        return purchaseFailed
I think it's better to rename it to `isPurchaseFailed`.

2023-06-08 14:40 UTC, Vladyslav-Kuksiuk commented on client/src/main/kotlin/io/spine/examples/shareaware/client/MarketPage.kt
> +        Preconditions.checkNotNull(share)
Let's import `checkNotNull` directly.

2023-06-09 12:44 UTC, armiol requested changes

2023-06-09 12:44 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/shareaware/client/MarketPage.kt
> +     * Page state when the user wants to purchase shares.
That's not English. Please rephrase.

2023-06-09 12:44 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/shareaware/client/MarketPage.kt
> +    public fun toPurchaseState(share: Share) {
Let's speak in terms of domain. E.g. `initiatePurchase` and `complete...`, `cancel...`, etc.

2023-06-09 12:44 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/shareaware/client/MarketPage.kt
> +    public fun purchaseState(): StateFlow<Boolean> {
`purchaseInProgress`?

2023-06-09 12:44 UTC, armiol commented on client/src/main/kotlin/io/spine/examples/shareaware/client/MarketPage.kt
> +    private val purchaseState: MutableStateFlow<Boolean> = MutableStateFlow(false)
I think we should have at least a separate type for this operation. 

Right now it's written in a procedural style.

2023-06-12 10:13 UTC, armiol approved these changes
Still with a number of both UI and implementation aspects to improve. But I think it's good enough for now.

Please feel free to merge, and let's start working on UI improvements.

2023-06-12 12:41 UTC, merged